### ISSUE TITLE
Unable to redirect to share admin dashboard

### ISSUE THREAD

**Issue by smb192** [dgradecak/alfresco-jwt-auth#1]
Hi,
Tried the configuration given in the ReadMe,but still share is not able to receive the token.
**Below are the share logs**

     Caused by: org.springframework.extensions.surf.exception.UserFactoryException: Unable to create user - failed to retrieve user metadata:
^[[34mshare_1     |^[[0m        at org.springframework.extensions.surf.support.AlfrescoUserFactory.loadUser(AlfrescoUserFactory.java:185)
 
     ERROR [alfresco.web.site] [http-nio-8080-exec-2] org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.extensions.surf.exception.UserFactoryException: Unable to retrieve user from repository
^[[34mshare_1     |^[[0m  org.springframework.extensions.surf.exception.UserFactoryException: Unable to retrieve user from repository
 
**Share config changes**
 <ssl-config>

            <verify-hostname>true</verify-hostname>
         </ssl-config>

         <connector>
            <id>alfrescoCookie</id>
            <name>Alfresco Connector</name>
            <description>Connects to an Alfresco instance using cookie-based authentication</description>
            <class>org.alfresco.web.site.servlet.SlingshotAlfrescoConnector</class>
         </connector>

         <connector>
            <id>alfrescoHeader</id>
            <name>Alfresco Connector</name>
            <description>Connects to an Alfresco instance using header and cookie-based authentication</description>
            
            <class>com.gradecak.alfresco.share.authorization.JwtAuthorizationAlfrescoConnector</class>
            <userHeader>X-Alfresco-Remote-User</userHeader>
            <jwtHeader>WEB_TOKEN</jwtHeader>
         </connector>

Please help us what could be the reason for the error in share.

**Comment by dgradecak** [comment]
Hi Sorry for my late reply ... I somehow missed your question here.

alfresco has a feature to create missing people by setting in global properties
create.missing.people=true

I recommend to either create the user in advance, either synchronize it from a remote server or add that property

**Comment by dgradecak** [comment]
@smb192 any feedback on this? 
is it ok to close the issue if it works for you?

**Comment by dgradecak** [comment]
feel free to reopen it
